'use strict';
// const values = [
//   ['B008KE7JLG',
//     'Wilton Perfect Results Premium Non-Stick Bar Baking Pan, 12-Cavity, Steel',
//     '',
//     917,
//     2.02163894423533],
//   ['B08Q35KPYN',
//     'Crimson Trace RAD Max Pro Large Open Reflex Rifle and Shotgun Sight with 3 MOA Red Dot Reticle, Auto Shutoff, Ambient Light and Shake to Wake Sensors for Firearms, Defensive Shooting and Competition',
//     '',
//     333,
//     0.734139333075644],
//   ['B08Q31NZFQ',
//     'Crimson Trace RAD Open Reflex Pistol Sight with 3 MOA LED Red Dot Reticle, Adjustable Brightness and Auto Shutoff Function for Full Size Handguns, Defensive Shooting and Competition',
//     '',
//     215,
//     0.473993863697488],
//   ['B081TJN9T8',
//     'TY Beanie Babies Sparkle Olaf Disney Frozen 2',
//     '',
//     59,
//     0.130072734689078],
//   ['B083ZZLZVN',
//     'STAR WARS The Vintage Collection ARC Trooper Fives Toy, 3.75-Inch-Scale The Clone Wars Action Figure, Toys for Kids Ages 4 and Up',
//     '',
//     50,
//     0.110231131092439],
//   ['B0BNWBN97S',
//     'LEGO Minifigures Disney 100 71038, Limited Edition Collectible Figures for Disney 100 Celebration, Gift to Encourage Kids Ages 5+ to Enjoy Independent Play (1 of 18 Bags to Collect)',
//     '',
//     140,
//     0.308647167058829],
//   ['B09YYT2XT5',
//     'Ty - Beanie Boo\'s - Luther The Dalmatian Soft Toy 15 cm - TY36389',
//     '',
//     91,
//     0.200620658588239],
//   ['B084R4F6BN',
//     'Funko Pop! Animation: Dragon Ball Super - Gohan Vinyl Figure',
//     '',
//     160,
//     0.352739619495805],
//   ['B01GVGIWGU',
//     'Ty Tabor - Pink & White Tiger Regular',
//     '',
//     91,
//     0.200620658588239],
//   ['B09YYT7M92',
//     'Ty Beanie Bellie Melly The Gray Koala - 6"',
//     '',
//     90,
//     0.19841603596639],
//   ['B09DWMTWN6',
//     'TY Beanie Mitzi - Gray cat - Reg',
//     '',
//     82,
//     0.1807790549916],
//   ['B09DWRFL47',
//     'Ty Beanie Ying - The Panda Bear - Reg',
//     '',
//     91,
//     0.200620658588239],
//   ['B08Y612QLM',
//     'TY 2007517 Muddles Brown & White Dog Beanie Boo Stuffed Animal, Multicoloured',
//     '',
//     109,
//     0.240303865781517],
//   ['B002Q4M5PQ',
//     'TY Beanie Boos Slush Dog',
//     '',
//     68,
//     0.149914338285717],
//   ['B07DPW1T3K',
//     'TY Catcher Dalmation - Beanie Babies, T42303',
//     '',
//     191,
//     0.421082920773117]
// ];
// const formulas = [
//   ['', '', '', '', '=CONVERT(K2, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K3, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K4, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K5, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K6, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K7, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K8, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K9, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K10, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K11, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K12, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K13, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K14, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K15, "g", "lbm")'],
//   ['', '', '', '', '=CONVERT(K16, "g", "lbm")']
// ];
// for (let x = 0; x < formulas.length; x++) {
//   const row = formulas[x];
//   for (let y = 0; y < row.length; y++) {
//     const cell = row[y];
//     if (cell === '') continue;
//     values[x][y] = cell;
//   }
// }
const pos = [
    ['Pending',
        'Fri Feb 23 2024 00:00:00 GMT -0800(Pacific Standard Time)',
        '',
        '10-00332',
        'Lovely',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Mon Mar 11 2024 00:00:00 GMT-0700(Pacific Daylight Time)',
        '',
        '10-00351',
        'Shiela',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Thu Feb 22 2024 00:00:00 GMT -0800(Pacific Standard Time)',
        '',
        '10-00330',
        'Shiela/Kesh',
        'Vendor -> Amz',
        'Pending',
        '',
        false,
        'PO Sent (PO Owner)',
        'Pending Action'],
    ['Pending',
        'Fri Feb 23 2024 00:00:00 GMT -0800(Pacific Standard Time)',
        '',
        '10-00332',
        'Lovely',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Fri Feb 23 2024 00:00:00 GMT -0800(Pacific Standard Time)',
        '',
        '10-00332',
        'Lovely',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Fri Feb 23 2024 00:00:00 GMT -0800(Pacific Standard Time)',
        '',
        '10-00332',
        'Lovely',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Fri Feb 23 2024 00:00:00 GMT -0800(Pacific Standard Time)',
        '',
        '10-00332',
        'Lovely',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Fri Feb 23 2024 00:00:00 GMT -0800(Pacific Standard Time)',
        '',
        '10-00332',
        'Lovely',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Fri Feb 23 2024 00:00:00 GMT -0800(Pacific Standard Time)',
        '',
        '10-00332',
        'Lovely',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Fri Feb 23 2024 00:00:00 GMT -0800(Pacific Standard Time)',
        '',
        '10-00332',
        'Lovely',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Fri Feb 23 2024 00:00:00 GMT -0800(Pacific Standard Time)',
        '',
        '10-00332',
        'Lovely',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Fri Feb 23 2024 00:00:00 GMT -0800(Pacific Standard Time)',
        '',
        '10-00332',
        'Lovely',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Mon Mar 11 2024 00:00:00 GMT-0700(Pacific Daylight Time)',
        '',
        '10-00351',
        'Shiela',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Mon Mar 11 2024 00:00:00 GMT-0700(Pacific Daylight Time)',
        '',
        '10-00351',
        'Shiela',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['Pending',
        'Mon Mar 11 2024 00:00:00 GMT-0700(Pacific Daylight Time)',
        '',
        '10-00351',
        'Shiela',
        'Vendor -> WH',
        'Pending',
        'Full',
        false,
        'PO Processing (Buying)',
        'Pending Action'],
    ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '', '', '', '', '', '', ''],
];
//# sourceMappingURL=quokka.js.map